name: CD
on:
  push:
    branches:
      - main
      # - feat/cicd
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check test status
        run: echo "::set-output name=tests-passed::$(grep -q '0 failing' test-results.txt && echo 'true' || echo 'false')"

      - name: Stop on test failure
        if: ${{steps.check-test-status.outputs.tests-passed == 'false'}}
        run: exit 1
