name: Release

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: fiap-irango-ecr

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  build:
    name: Build Docker Image
    needs: [lint]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image_uri: ${{ steps.image_uri.outputs.image_uri }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mask-aws-account-id: 'no'

      - id: login_ecr
        name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - id: get_branch
        name: Extract branch name
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - id: image_uri
        name: Create image name
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          REPO_NAME: ${{ github.event.repository.name }}
          BRANCH_NAME: ${{ steps.get_branch.outputs.branch }}
          IMAGE_HASH: ${{ github.sha }}
        run: echo "image_uri=${ECR_REGISTRY}/${ECR_REPOSITORY}:${REPO_NAME}_${BRANCH_NAME}_${IMAGE_HASH}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
          DOCKERFILE_PATH: Dockerfile
          IMAGE_URI: ${{ steps.image_uri.outputs.image_uri }}
        run: |
          docker build \
            --build-arg BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM} \
            -f ${DOCKERFILE_PATH} \
            -t ${IMAGE_URI} .

      - name: Push image to ECR
        run: |
          docker push ${{ steps.image_uri.outputs.image_uri }}

  post_build:
    name: Post Build
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Trigger K8s Workflow
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          IMAGE_URI: ${{ needs.build.outputs.image_uri }}
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.github.com/repos/${{github.repository_owner}}/fiap-irango-k8s/actions/workflows/release-api.yml/dispatches
          method: POST
          headers: '{"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}'
          bearer-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          body: '{"ref": "main", "inputs": {"image_uri": "${IMAGE_URI}"}}'
          log-response: true
